plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.kapt'
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.9.25'
    //id 'org.jetbrains.kotlin.jvm' version '1.9.23'

    // TM  needed for JsonAdapter error
    id("com.google.devtools.ksp") version "1.9.25-1.0.20"

    // Apply the Google services plugin
    id 'com.google.gms.google-services'
    // Apply the Firebase Crashlytics plugin
    id 'com.google.firebase.crashlytics'
}

def keystorePropertiesFile = new File(rootProject.projectDir, 'keystore.properties')

android {
    namespace "org.tyndalebt.storyproduceradv"
    // buildToolsVersion '33.0.1'
    defaultConfig {
        applicationId "org.tyndalebt.storyproduceradv"
        minSdk 24
        compileSdk 34
        targetSdk 34
        versionCode 70
        versionName '2.36'
        vectorDrawables.useSupportLibrary = true
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    signingConfigs {
        if (keystorePropertiesFile.isFile()) {
            logger.lifecycle("keystore.properties exists. Sign APK.")
            def keystoreProperties = new Properties()
            keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
            release {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile rootProject.file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
            }
        }
        else
        {
            logger.lifecycle("keystore.properties not found. Unable to sign APK.")
        }
    }
    applicationVariants.all { variant ->
        variant.outputs.all {
            def versionPart = variant.name
            if (variant.name != "debug") {
                if (keystorePropertiesFile.isFile()) {
                    versionPart = variant.versionName
                } else {
                    versionPart = versionPart + "-not-signed"
                }
            }
            outputFileName = "SP-${versionPart}.apk"
        }
    }
    buildTypes {
        release {
            debuggable false
            if (keystorePropertiesFile.isFile()) {
                signingConfig signingConfigs.release
            } else {
                signingConfig signingConfigs.debug
            }
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            // dkh 4/4/2022 - OR12 disable firebase analytics for SPadvance because the SPadvance
            // release number shows up in the firebase website (get mixed SPadvance and SP crashes
            // showing up
            resValue("bool", "FIREBASE_ANALYTICS_DEACTIVATED", "true")
            buildConfigField "String", "ROCC_URL_PREFIX", ROCC_URL_PREFIX
            buildConfigField "String", "ROCC_WEBSOCKETS_PREFIX", ROCC_WEBSOCKETS_PREFIX
            buildConfigField "Boolean", "ENABLE_IN_APP_ROCC_URL_SETTING", "false"
            resValue "bool", "enable_in_app_rocc_url_setting", "false"
        }
        // dkh - 5/3/21  - These changes came  from Chris Hubbard (pull request 568)
        // Updated applicationIdSuffix to allow debug versions of app crashes to be captured separate from
        // continuous build app crashes or product builds app crashes in Firebase.
        // Also, make sure we capture analytics by
        // setting FIREBASE_ANALYTICS_DEACTIVATED to false.
        //"package_name" in debug\google-services.json was also changed.  Side effect of
        // changing the package_name is that field names in the JSON registration parsing were
        // affected.  See Issue #559 for a more detailed explanation.
        //
        debug {
            debuggable true
            versionNameSuffix ".debug"
            //applicationIdSuffix "debug"
            // dkh 4/4/2022 - OR12 disable firebase analytics for SPadvance because the SPadvance
            // release number shows up in the firebase website (get mixed SPadvance and SP crashes
            // showing up
            resValue("bool", "FIREBASE_ANALYTICS_DEACTIVATED", "true")
            buildConfigField "String", "ROCC_URL_PREFIX", ROCC_URL_PREFIX
            buildConfigField "String", "ROCC_WEBSOCKETS_PREFIX", ROCC_WEBSOCKETS_PREFIX
            buildConfigField "Boolean", "ENABLE_IN_APP_ROCC_URL_SETTING", "false"
            resValue "bool", "enable_in_app_rocc_url_setting", "false"
            signingConfig signingConfigs.debug
        }
        continuous {
            initWith release
            applicationIdSuffix ".ci"
            // dkh 4/4/2022 - OR12 disable firebase analytics for SPadvance because the SPadvance
            // release number shows up in the firebase website (get mixed SPadvance and SP crashes
            // showing up
            resValue("bool", "FIREBASE_ANALYTICS_DEACTIVATED", "true")
        }
    }
    productFlavors {
    }
    packagingOptions {
        resources {
            pickFirsts += ['META-INF/atomicfu.kotlin_module']
        }
    }
    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }

    kotlinOptions {
        jvmTarget = '17' // Or your desired JVM target version
        freeCompilerArgs += [
                "-opt-in=kotlin.RequiresOptIn",   // TM  changed from -Xopt-in
                "-Xstring-concat=inline"
        ]
    }
    lint {
        abortOnError false
    }
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.9.25'
    // TM  needed for JsonAdapter error
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.2")
    // the following line eliminates the dup class error somehow - Tim
    implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0'
    implementation 'org.java-websocket:Java-WebSocket:1.6.0'
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.10.0'
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.preference:preference:1.2.1'
//    implementation 'net.i2p.android.ext:floatingactionbutton:1.10.1'
//    implementation 'com.github.futuresimple:android-floating-action-button:1.10.1'
    implementation 'androidx.legacy:legacy-support-v13:1.0.0'   // TIM
    implementation 'com.googlecode.mp4parser:isoparser:1.1.22'
    implementation "commons-io:commons-io:2.15.0"
//    implementation 'org.apache.commons:commons-io:2.15.1'
    implementation 'com.android.volley:volley:1.2.1'

// needed for ffmpeg dependency is no longer available - should be in spadv/app/libs folder
    implementation(files("Libs/mobile-ffmpeg-full-gpl-4.4.LTS.aar"))
//    implementation 'com.arthenica:mobile-ffmpeg-full:4.2.2.LTS'
//    implementation 'com.arthenica:ffmpeg-kit-full:6.0-2'
    implementation 'com.arthenica:smart-exception-java:0.2.1'
    implementation 'com.google.code.gson:gson:2.13.2'
    implementation 'com.google.firebase:firebase-analytics:17.6.0'
    implementation 'com.google.firebase:firebase-crashlytics:17.2.2'
    implementation 'com.github.codekidX:storage-chooser:2.0.4.4'

    implementation 'com.squareup.moshi:moshi:1.15.2'
    implementation 'com.squareup.moshi:moshi-kotlin:1.15.2'
    ksp 'com.squareup.moshi:moshi-kotlin-codegen:1.15.2'

    implementation 'com.opencsv:opencsv:5.12.0'
    implementation 'org.jsoup:jsoup:1.21.2'
    //implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    //implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.webkit:webkit:1.14.0'
    implementation 'com.google.firebase:firebase-core:17.2.2'
    implementation 'com.google.firebase:firebase-messaging:23.0.8'
    implementation 'net.lingala.zip4j:zip4j:2.11.5'

    implementation 'io.reactivex.rxjava2:rxkotlin:2.4.0'
    // It is recommended to explicitly add the RxJava2 dependency as well
    implementation 'io.reactivex.rxjava2:rxjava:2.2.10'
    // If you need Android-specific bindings (e.g., mainThread scheduler)
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'

    // DKH - 08/26/2021 Added by Cedarville for Wordlinks
    // implementation 'androidx.coordinatorlayout:coordinatorlayout:1.1.0'
    // Issue 166, Cedarville pull #519
    implementation 'androidx.coordinatorlayout:coordinatorlayout:1.3.0'
    //  was told the following line was not supported.. replaced with the line below
    //   but both of the two lines below that were also mentioned in the website
    //   https://stackoverflow.com/questions/57655435/what-replaced-appcompat-v7-in-androidx
    //implementation 'com.android.support:appcompat-v7:28.0.0'
    //implementation 'androidx.cardview:cardview:1.0.0'
    //implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.2' // Or the latest 6.x.x version
//    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:6.0.1' // Or the latest 6.x.x version
    testImplementation 'androidx.test:core:1.5.0'   // TM
    //testImplementation 'org.robolectric:robolectric:4.9'
    testImplementation 'org.robolectric:robolectric:4.16'
    testImplementation 'org.mockito:mockito-core:5.20.0'

    //androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test:runner:1.5.0'
    //androidTestImplementation 'androidx.annotation:annotation:1.1.0'
    androidTestImplementation 'androidx.test:rules:1.6.1'   // TM
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.6.1'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.3.0'
    implementation 'com.jakewharton.timber:timber:5.0.1'

    // Replace bundled strings dynamically
    implementation 'dev.b3nedikt.restring:restring:6.0.0'    // TM

    // Intercept view inflation
    implementation 'dev.b3nedikt.viewpump:viewpump:4.0.14'

    // Allows to update the text of views at runtime without recreating the activity
    implementation 'dev.b3nedikt.reword:reword:4.0.4'

    // Jackson
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.1'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.17.1'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.17.1'

    // ftp
    implementation 'commons-net:commons-net:3.11.1'
}

